version: '3'
services:
  web:
    build: '.'
    ports:
      - "5003:5000"
    restart: unless-stopped


      
  #   depends_on:
  #       - mongo
  # mongo:
  #   image: mongo
  #   restart: always

