version: '3'
services:
  web:
    build: '.'
    ports:
<<<<<<< HEAD
      - "5003:5000"
=======
      - "5001:5000"
>>>>>>> 929fc19250c1825b061f6600e40e1784bf0f6303


      
  #   depends_on:
  #       - mongo
  # mongo:
  #   image: mongo
  #   restart: always

